Feat/firebase authentication
P-r4Tes/Calendar-App pull request #7
Opened 2024-03-04 02:54 UTC by SayisMe

2024-03-04 03:35 UTC, vinivin153 approved these changes
👍🏼

2024-03-04 03:35 UTC, vinivin153 commented on firebase/firebasedb.ts
> +};
찬섭님이 작성한 src/constants/firebase.ts 이용해도 좋을 것 같습니다!

2024-03-04 04:19 UTC, yeongjunekoh requested changes
전반적으로 작업하신 사항들 모두 확인하였습니다!

카카오와 소셜 로그인 연동 부분은 아직 안되어있는 것으로 확인했습니다:D

요것은 폴더 구조와 관련된 것인데, `component`안에 `LoginForm`과 같은 폴더를 만든 뒤에 세부 사항에서 `index.tsx`처럼 관리하는 것이 어떨지요?

```
components
| - LoginForm
|   | - index.tsx
|   | - index.module.css
| - SignupForm
|   | - index.tsx
|   | - index.module.css
```

해당 부분은 저희 모두 공통적으로 맞춰야 하는 부분이기에 논의에 한 번 올리도록하겠습니다!

+) PR도 문서화를 신경쓰면 어떨까라는 생각입니다!

2024-03-04 04:19 UTC, yeongjunekoh commented on firebase/firebasedb.ts
> +};
동의합니다! 동일한 폴더/파일에 객체로 관리되면 더욱 좋을 것같아요

2024-03-04 04:19 UTC, yeongjunekoh commented on src/components/LoginForm.tsx
> +import styles from './Form.module.css'; // CSS 모듈
`//css 모듈`라는 주석은 불필요한 주석인 것같습니다!

이미 파일명과 어디에서 import 해왔는지 등을 보면 CSS 모듈임을 알 수 있기 때문입니다!

2024-03-04 04:19 UTC, yeongjunekoh commented on src/components/LoginForm.tsx
> +
카카오 로그인은 아직 완료단계가 아닌 것이죠??

2024-03-09 07:17 UTC, SayisMe commented on firebase/firebasedb.ts
> +};
찬섭님께서 작성해주신 동일 파일로 수정완료하였습니다 ✅

2024-03-09 07:19 UTC, SayisMe commented on src/components/LoginForm.tsx
> +
넵 카카오 로그인은 firebase authentication에서 제공업체로 따로 분류되어있지 않아서 아직 진행하지 않았습니다.
추후에 추가로 진행해보겠습니다! 👍🏻

2024-03-09 07:20 UTC, SayisMe commented on src/components/LoginForm.tsx
> +import styles from './Form.module.css'; // CSS 모듈
- LoginForm.tsx, SignUpForm.tsx 에서 불필요한 주석들 전부 제거완료하였습니다 ✅

2024-03-09 09:40 UTC, SayisMe commented
- [x] firebaseConfig를 통합시켰습니다.
- [x] tailwind를 이용하여 CSS를 수정하였습니다.
- [x] jest test code (user) 를 일부 수정하였습니다.
- [x] firebase authentication을 적용하였습니다.
- [x] 로그인시 firestore에 유저 정보가 uid를 기준으로 저장되도록 하였습니다.

@yeongjunekoh @vinivin153 

Code Review 꼼꼼히 해주심에 감사드립니다 👍🏻

2024-03-09 09:40 UTC, merged